menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# valine comment
valine: false
leancloud_id: 
leancloud_key: 

# disqus comment
disqus: true
disqus_shortname: xuzhenglun

# google analytics
googleTrackId: UA-57211109-1
