#You can eidt the color scheme in source/css/_base/variable.styl

photo: /icon.jpg

email: 
twitter: 
facebook: 
googleplus: "+徐正伦"
github: xuzhenglun
pinterest: 
linkedin: 
instagram: 
zhihu: 
weibo: 
renren: 


addthis:
  enable: true
  pubid:
  facebook: true
  twitter: false
  google: true
  pinterest: true

fancybox: true

#
bighomepage: true

#Use cdnjs' CDN
usecdn: false

google_analytics: UA-57211109-1
rss: /atom.xml

forvirgo: true
